### ISSUE TITLE
I the project stale?

### ISSUE THREAD

**Issue by konste** [TerribleDev/TimberWinR#61]
I see all nuget packages used are obsolete and I cannot make it work with Elasticsearch 2.0

Is the project abandoned?

Konstantin

**Comment by ryanbreen** [comment]
Yes, this project is abandoned.  We are no longer using ELK, so we are no longer developing TimberWinR.  We are happy to transfer this project to an interested owner.

I just updated the readme to reflect this.

**Comment by pbolduc** [comment]
What did you switch to from ELK?

**Comment by ryanbreen** [comment]
We switched to LogEntries. We found we were spending an awful lot of time and money maintaining our ELK infrastructure.

**Comment by MyKEcz** [comment]
I hope somebody will continue develop on this project. Thank you @ryanbreen and whole your team!
